FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build-env
WORKDIR /App
COPY . ./

# install nuget packages
RUN dotnet restore 
# publish project to a folder called 'out'
RUN dotnet publish -c Release -o out -r linux-x64

# put it into a final image
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /App
COPY --from=build-env /App/out .

# expose on port 80
ENV ASPNETCORE_URLS=http://+:80
EXPOSE 80

ENTRYPOINT ["dotnet", "SearchApi.dll"]